# Generated by Django 4.2.7 on 2025-12-23 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='strategic_plans/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Strategic Plan',
                'verbose_name_plural': 'Strategic Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategicPlanSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='strategic_plans/sections/%Y/%m/%d/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.strategicplan')),
            ],
            options={
                'verbose_name': 'Strategic Plan Section',
                'verbose_name_plural': 'Strategic Plan Sections',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
