# Generated by Django 4.2.7 on 2025-12-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_strategicplan_strategicplansection'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
