# Generated by Django 4.2.7 on 2025-12-24 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_history_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Value name (e.g., Integrity, Commitment)', max_length=255)),
                ('description', models.TextField(help_text='Description of the core value')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StrategicPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Strategic Priorities', max_length=255)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='about/strategic/%Y/%m/%d/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Strategic Priority',
                'verbose_name_plural': 'Strategic Priorities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisionMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_title', models.CharField(default='Our Vision', max_length=255)),
                ('vision_text', models.TextField(help_text='Vision statement content')),
                ('mission_title', models.CharField(default='Our Mission', max_length=255)),
                ('mission_text', models.TextField(help_text='Mission statement content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='about/vision_mission/%Y/%m/%d/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vision and Mission',
                'verbose_name_plural': 'Vision and Mission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='historyimage',
            options={'ordering': ['order'], 'verbose_name': 'History Image', 'verbose_name_plural': 'History Images'},
        ),
        migrations.AlterField(
            model_name='abouthistory',
            name='image',
            field=models.ImageField(blank=True, help_text='Featured image for the history section', null=True, upload_to='about/history/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='abouthistory',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Introductory text (e.g., university name in uppercase)', max_length=255),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='description',
            field=models.TextField(blank=True, help_text='Event description'),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='title',
            field=models.CharField(help_text='Event title', max_length=255),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='year',
            field=models.CharField(help_text='Year or date range (e.g., "1948" or "1948-1950")', max_length=50),
        ),
        migrations.AlterField(
            model_name='historyimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Image caption or description', max_length=255),
        ),
        migrations.AlterField(
            model_name='historyimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/history/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='historyimage',
            name='year',
            field=models.CharField(blank=True, help_text='Year associated with the image', max_length=50),
        ),
        migrations.CreateModel(
            name='PriorityItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Priority item text', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.strategicpriority')),
            ],
            options={
                'verbose_name': 'Priority Item',
                'verbose_name_plural': 'Priority Items',
                'ordering': ['order'],
            },
        ),
    ]
