# Generated by Django 4.2.7 on 2025-12-24 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_corevalue_strategicpriority_visionmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Position title (e.g., Chancellor)', max_length=255)),
                ('hierarchy_level', models.IntegerField(choices=[(1, 'Top Level - Chancellor/Vice-Chancellor'), (2, 'Senior - Pro-Vice-Chancellor/Registrar'), (3, 'Director/Department Head')], default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leader Position',
                'verbose_name_plural': 'Leader Positions',
                'ordering': ['hierarchy_level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(help_text='Professional headshot', upload_to='leaders/%Y/%m/%d/')),
                ('bio', models.TextField(blank=True, help_text='Short biography')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within position level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaders', to='api.leaderposition')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leader',
                'verbose_name_plural': 'Leaders',
                'ordering': ['position__hierarchy_level', 'order', 'name'],
            },
        ),
    ]
