# Generated by Django 4.2.7 on 2025-12-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_policydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicplansection',
            name='items',
            field=models.JSONField(blank=True, help_text='List of items as JSON array of objects with title/description', null=True),
        ),
        migrations.AddField(
            model_name='strategicplansection',
            name='section_type',
            field=models.CharField(choices=[('overview', 'Overview'), ('vision_commitment', 'Vision & Strategic Commitments'), ('objectives', 'Strategic Plan Objectives'), ('goals', 'Goals')], default='overview', max_length=50),
        ),
        migrations.AddField(
            model_name='strategicplansection',
            name='subheading',
            field=models.CharField(blank=True, help_text='Optional subtitle or description', max_length=255),
        ),
        migrations.AlterField(
            model_name='strategicplansection',
            name='content',
            field=models.TextField(blank=True, help_text='Rich text content for the section'),
        ),
    ]
