# Generated by Django 4.2.7 on 2025-12-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_strategicplansection_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Academics', max_length=255)),
                ('hero_subtitle', models.CharField(default='Academic work is one of the most crucial aspects of the university experience and, therefore, requires discipline and commitment.', max_length=500)),
                ('overview_title', models.CharField(default='Academic Excellence', max_length=255)),
                ('overview_description', models.TextField(default='ETU offers a comprehensive range of academic programs across multiple faculties and disciplines.')),
                ('nurture_title', models.CharField(default='Nurturing Success', max_length=255)),
                ('nurture_description', models.TextField(default='Our serene atmosphere fosters academic excellence, empowering individuals to thrive in their diverse educational pursuits')),
                ('study_with_us_link', models.URLField(blank=True, help_text='Link to "Study with us" section')),
                ('student_handbook_link', models.URLField(blank=True, help_text='Link to student handbook')),
                ('academic_calendar_link', models.URLField(blank=True, help_text='Link to academic calendar')),
                ('academic_calendar_title', models.CharField(default='Academic Calendar', max_length=255)),
                ('academic_calendar_description', models.TextField(default='See the academic calendar for various schedules and activities for the current academic year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Page',
                'verbose_name_plural': 'Academic Pages',
            },
        ),
        migrations.CreateModel(
            name='AcademicStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic_type', models.CharField(choices=[('courses', 'Courses Offered'), ('undergrad', 'Undergraduate Programmes'), ('graduate', 'Graduate Programmes'), ('faculty', 'Faculty Members'), ('students', 'Students')], max_length=20, unique=True)),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Statistic',
                'verbose_name_plural': 'Academic Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('undergraduate', 'Undergraduate Admissions'), ('graduate', 'Graduate Admissions'), ('postfirst', 'Post-first degree Admissions')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='admissions/%Y/%m/%d/')),
                ('link_url', models.URLField(blank=True, help_text='External link for the admission type')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission Type',
                'verbose_name_plural': 'Admission Types',
                'ordering': ['order'],
            },
        ),
    ]
