with open('backend/api/admin.py', 'a') as f:
    f.write('\n\n@admin.register(PolicyDocument)\nclass PolicyDocumentAdmin(admin.ModelAdmin):\n')
    f.write('    list_display = ("title", "order", "file_name", "created_at")\n')
    f.write('    search_fields = ("title", "short_description")\n')
    f.write('    readonly_fields = ("created_at", "updated_at")\n')
    f.write('    ordering = ("order", "title")\n')
    f.write('    fieldsets = (\n')
    f.write('        ("Content", {"fields": ("title", "short_description", "file")}),\n')
    f.write('        ("Display", {"fields": ("order",)}),\n')
    f.write('        ("Timestamps", {"fields": ("created_at", "updated_at")}),\n')
    f.write('    )\n')
    f.write('\n    def file_name(self, obj):\n')
    f.write('        if obj.file:\n')
    f.write('            return obj.file.name.split("/")[-1]\n')
    f.write('        return "No file"\n')
    f.write('    file_name.short_description = "File"\n')
print("PolicyDocumentAdmin appended")
